# This is a basic workflow to help you get started with Actions

name: 'Deploy on Google Cloud'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Push to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Connection
        run: ssh -i $ {{ secrets.DEPLOY }} 34.123.248.52
      - name: Workdir
        run: cd SpotifyAPI
      - name: Update
        run: git pull -r origin main
      - name: Build
        run: docker-compose build
      - name: Run
        run: docker-compose up -d
  
