# This is a basic workflow to help you get started with Actions

name: 'Deploy on Google Cloud'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Push to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H 34.123.248.52 >> ~/.ssh/known_hosts
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: "34.123.248.52"
          username: "cc002"
          key: ${{ secrets.DEPLOY }}
          port: "22"
          script: |
            cd SpotifyAPI
            git pull -r origin main
            docker-compose build
            docker-compose up -d
  
